using System;

namespace D2Packets
{
    public enum GameClientPacket
    {
        WalkToLocation              = 0x01,
        WalkToTarget                = 0x02,
        RunToLocation               = 0x03,
        RunToTarget                 = 0x04,
        CastLeftSkill               = 0x05,
        CastLeftSkillOnTarget       = 0x06,
        CastLeftSkillOnTargetStopped = 0x07,
        RecastLeftSkill             = 0x08,
        RecastLeftSkillOnTarget     = 0x09,
        RecastLeftSkillOnTargetStopped = 0x0A,
        CastRightSkill              = 0x0C,
        CastRightSkillOnTarget      = 0x0D,
        CastRightSkillOnTargetStopped = 0x0E,
        RecastRightSkill            = 0xF,
        RecastRightSkillOnTarget    = 0x10,
        RecastRightSkillOnTargetStopped = 0x11,
        UnitInteract                = 0x13,
        SendOverheadMessage         = 0x14,
        SendMessage                 = 0x15,
        PickItem                    = 0x16,
        DropItem                    = 0x17,
        DropItemToContainer         = 0x18,
        PickItemFromContainer       = 0x19,
        EquipItem                   = 0x1a,
        UnequipItem                 = 0x1c,
        SwapEquippedItem            = 0x1d,
        SwapContainerItem           = 0x1f,
        UseInventoryItem            = 0x20,
        StackItems                  = 0x21,
        AddBeltItem                 = 0x23,
        RemoveBeltItem              = 0x24,
        SwapBeltItem                = 0x25,
        UseBeltItem                 = 0x26,
        IdentifyItem                = 0x27,
        EmbedItem                   = 0x29,
        ItemToCube                  = 0x2a,
        TownFolkInteract            = 0x2f,
        TownFolkCancelInteraction   = 0x30,
        DisplayQuestMessage         = 0x31,
        BuyItem                     = 0x32,
        SellItem                    = 0x33,
        CainIdentifyItems           = 0x34,
        TownFolkRepair              = 0x35,
        HireMercenary               = 0x36,
        IdentifyGambleItem          = 0x37,
        TownFolkMenuSelect          = 0x38,
        IncrementAttribute          = 0x3a,
        IncrementSkill              = 0x3b,
        SelectSkill                 = 0x3C,
        HoverUnit                   = 0x3d,
        SendCharacterSpeech         = 0x3f,
        RequestQuestLog             = 0x40,
        Respawn                     = 0x41,
        WaypointInteract            = 0x49,
        RequestReassign             = 0x4b,
        ClickButton                 = 0x4f,
        DropGold                    = 0x50,
        SetSkillHotkey              = 0x51,
        CloseQuest                  = 0x58,
        GoToTownFolk                = 0x59,
        SetPlayerRelation           = 0x5d,
        PartyRequest                = 0x5e,
        UpdatePosition              = 0x5f,
        SwitchWeapons               = 0x60,
        ChangeMercEquipment         = 0x61,
        ResurrectMerc               = 0x62,
        InventoryItemToBelt         = 0x63,
        WardenResponse              = 0x66,
        GameLogonRequest            = 0x68,
        ExitGame                    = 0x69,
        EnterGame                   = 0x6b,
        Ping                        = 0x6d,

        Invalid                     = 0x6E,

        Wrapper                     = 0xF00,
        GoToLocation                = 0xF01,
        GoToTarget                  = 0xF02
    }
}